# Generated by Django 3.2.12 on 2022-03-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.topic', verbose_name='Тема'),
        ),
    ]
