# Generated by Django 3.2.13 on 2022-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Официальное название'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
