# Generated by Django 3.2.10 on 2022-02-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220130_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
