# Generated by Django 3.2.10 on 2022-02-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220203_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', to='core.Subject'),
        ),
    ]
