# Generated by Django 3.2.13 on 2022-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_plugin_month_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='subjects',
            field=models.ManyToManyField(related_name='klass', to='core.Subject'),
        ),
    ]
