# Generated by Django 3.2.13 on 2022-07-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('core', '0004_alter_klass_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Вид работы')),
                ('weight', models.FloatField(default=1, verbose_name='Коэффицент')),
                ('notify', models.BooleanField(default=False, verbose_name='Оповещать учеников')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.klass', verbose_name='Класс')),
                ('students', models.ManyToManyField(to='authentication.Student', verbose_name='Отображаемые ученики')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Quarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], unique=True, verbose_name='Четверть')),
                ('begin', models.DateField(verbose_name='Начало четверти')),
                ('end', models.DateField(verbose_name='Конец четверти')),
            ],
            options={
                'verbose_name': 'Четверть',
                'verbose_name_plural': 'Четверти',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('theme', models.CharField(blank=True, max_length=120, verbose_name='Тема')),
                ('is_planned', models.BooleanField(default=False, verbose_name='Запланирован')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.control', verbose_name='Вид работы')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Группа')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.quarters', verbose_name='Четверть')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['date'],
            },
        ),
    ]
