# Generated by Django 3.2.10 on 2022-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_klass_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Плагин',
                'verbose_name_plural': 'Плагины',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='plugins',
            field=models.ManyToManyField(blank=True, to='core.Plugin'),
        ),
    ]
