# Generated by Django 3.2.13 on 2022-07-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_control_group_lesson_quarters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quarters',
            new_name='Quarter',
        ),
    ]
