# Generated by Django 3.2.10 on 2022-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220203_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='icon',
            field=models.ImageField(blank=True, upload_to='plugins/', verbose_name='Иконка'),
        ),
    ]
