# Generated by Django 3.2.13 on 2022-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_quarters_quarter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='control',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Вид работы'),
        ),
        migrations.AlterField(
            model_name='control',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Оповещать учеников о предстоящих работах'),
        ),
    ]
