# Generated by Django 3.2.13 on 2022-07-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_bell_school'),
        ('authentication', '0003_remove_user_school'),
        ('core', '0007_auto_20220708_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klass',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
