# Generated by Django 3.2.14 on 2022-07-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220725_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plugin',
        ),
    ]
