# Generated by Django 3.2.14 on 2022-07-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_plugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.FileField(blank=True, upload_to='subjects/', verbose_name='Иконка'),
        ),
    ]
