# Generated by Django 3.2.12 on 2022-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_school_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.IntegerField(default=1, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'group')},
        ),
    ]
