# Generated by Django 3.2.10 on 2022-02-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_last_login'),
        ('core', '0007_alter_klass_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='authentication.Student'),
        ),
    ]
