# Generated by Django 3.2.10 on 2022-02-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_klass_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='month_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Месячная стоимость'),
        ),
        migrations.AlterField(
            model_name='school',
            name='plugins',
            field=models.ManyToManyField(blank=True, related_name='schools', to='core.Plugin', verbose_name='Плагины'),
        ),
    ]
