# Generated by Django 3.2.12 on 2022-03-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220207_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='title',
            new_name='name',
        ),
    ]
