# Generated by Django 3.2.15 on 2022-08-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20220710_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
    ]
