# Generated by Django 3.2.10 on 2022-02-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220203_1601'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='TimetableLesson',
        ),
        migrations.AlterModelOptions(
            name='bell',
            options={'ordering': ['n'], 'verbose_name': 'Звонок', 'verbose_name_plural': 'Звонки'},
        ),
        migrations.RemoveField(
            model_name='bell',
            name='timetable',
        ),
        migrations.AddField(
            model_name='bell',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
