# Generated by Django 3.2.13 on 2022-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablelesson',
            name='group',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III')], default=1, verbose_name='Группа'),
        ),
    ]
