# Generated by Django 3.2.13 on 2022-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_klass_subjects'),
        ('timetable', '0002_timetablelesson_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablelesson',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='День недели'),
        ),
        migrations.AlterUniqueTogether(
            name='timetablelesson',
            unique_together={('number', 'day', 'klass', 'group')},
        ),
    ]
