# Generated by Django 3.2.10 on 2022-02-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20220203_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetablelesson',
            options={'ordering': ['klass', 'number'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='timetablelesson',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')], verbose_name='День недели'),
        ),
    ]
