# Generated by Django 3.2.13 on 2022-05-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_klass_subjects'),
        ('timetable', '0003_auto_20220501_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablelesson',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='timetablelesson',
            name='group',
            field=models.IntegerField(choices=[(0, '-'), (1, 'I'), (2, 'II'), (3, 'III')], default=1, verbose_name='Группа'),
        ),
        migrations.AlterUniqueTogether(
            name='timetablelesson',
            unique_together={('number', 'day', 'klass', 'group', 'subject')},
        ),
    ]
