# Generated by Django 3.2.13 on 2022-07-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20220610_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bell',
            name='school',
        ),
    ]
