# Generated by Django 3.2.15 on 2022-08-29 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_rename_subjects_group_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minimum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(4)], verbose_name='Класс')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.quarter', verbose_name='Четверть')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Образовательный минимум',
                'verbose_name_plural': 'Образовательные минимумы',
                'ordering': ['grade', 'subject', 'quarter'],
            },
        ),
    ]
