# Generated by Django 3.2.15 on 2022-08-29 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minimum',
            options={'ordering': ['grade', 'subject', 'quarter'], 'verbose_name': 'Минимум', 'verbose_name_plural': 'Минимумы'},
        ),
        migrations.AlterField(
            model_name='minimum',
            name='grade',
            field=models.IntegerField(choices=[(4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(4)], verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='minimum',
            name='subject',
            field=models.CharField(choices=[('Информатика', 'Информатика'), ('История', 'История'), ('Литература', 'Литература'), ('Математика', 'Математика'), ('Обществознание', 'Обществознание'), ('Русский язык', 'Русский язык'), ('Хим-Био', 'Хим-Био'), ('Экономика', 'Экономика'), ('Физика', 'Физика')], max_length=100, verbose_name='Предмет'),
        ),
    ]
