# Generated by Django 3.2.10 on 2022-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', 'System'), ('headteacher', 'Headteacher'), ('event', 'Event')], default='system', max_length=255),
        ),
    ]
